STRINGS = GLOBAL.STRINGS
RECIPETABS = GLOBAL.RECIPETABS
Recipe = GLOBAL.Recipe
Ingredient = GLOBAL.Ingredient
TECH = GLOBAL.TECH


--ARMOR
--ARMOR
--ARMOR


--Grass Suit
TUNING.ARMORGRASS = 300
TUNING.ARMORGRASS_ABSORPTION = 0.65

--Log Suit
TUNING.ARMORWOOD = 600
TUNING.ARMORWOOD_ABSORPTION = 0.75

--Night Armor
TUNING.ARMOR_SANITY = 1200
TUNING.ARMOR_SANITY_ABSORPTION = 0.90

--Scalemail
TUNING.ARMORDRAGONFLY = 3000
TUNING.ARMORDRAGONFLY_ABSORPTION = 0.9

--Marble Suit
TUNING.ARMORMARBLE = 3000
TUNING.ARMORMARBLE_ABSORPTION = 0.95

--Thulecite Suit
TUNING.ARMORRUINS = 7000
TUNING.ARMORRUINS_ABSORPTION = 0.95


--HELMETS
--HELMETS
--HELMETS


--Football Helmet
TUNING.ARMOR_FOOTBALLHAT = 450
TUNING.ARMOR_FOOTBALLHAT_ABSORPTION = 0.80

--Shelmet
TUNING.ARMOR_SLURTLEHAT = 1000
TUNING.ARMOR_SLURTLEHAT_ABSORPTION = 0.90

--Thulecite Crown
TUNING.ARMOR_RUINSHAT = 4000
TUNING.ARMOR_RUINSHAT_ABSORPTION = 0.90

--Beekeeper Hat
TUNING.ARMOR_BEEHAT = 1000
TUNING.ARMOR_BEEHAT_ABSORPTION = 1.00



